"use server"
import { revalidatePath } from "next/cache"
import { requireUser } from "@/lib/auth/session"
import { prisma } from "@/lib/db/prisma"
import { parseMoneyInput } from "@/lib/money/currency"
import type { BudgetFormState } from "@/features/budgets/types"

function parseMonth(value: string) { if (!/^\d{4}-\d{2}$/.test(value)) return null; const date = new Date(`${value}-01T00:00:00.000Z`); return Number.isNaN(date.getTime()) ? null : date }
function refreshBudgets() { revalidatePath("/"); revalidatePath("/budgets") }
async function validateBudget(userId: string, formData: FormData, excludeId?: string) { const scope = String(formData.get("scope") ?? ""); const amount = parseMoneyInput(String(formData.get("amount") ?? "")); const month = parseMonth(String(formData.get("month") ?? "")); const categoryId = String(formData.get("categoryId") ?? "") || null; if ((scope !== "TOTAL" && scope !== "CATEGORY") || amount === null || amount <= 0 || !month || (scope === "CATEGORY" && !categoryId)) return { error: "Enter valid budget details." } as const; if (scope === "CATEGORY") { const category = await prisma.category.findFirst({ where: { id: categoryId!, userId, type: "EXPENSE", isArchived: false }, select: { id: true } }); if (!category) return { error: "Choose an active expense category." } as const } const duplicate = await prisma.budget.findFirst({ where: { userId, month, scope, categoryId: scope === "CATEGORY" ? categoryId : null, ...(excludeId ? { id: { not: excludeId } } : {}) }, select: { id: true } }); if (duplicate) return { error: "A matching budget already exists for this month." } as const; return { data: { scope, amount, month, categoryId: scope === "CATEGORY" ? categoryId : null } } as const }
export async function createBudgetAction(_: BudgetFormState, formData: FormData): Promise<BudgetFormState> { const user = await requireUser(); const parsed = await validateBudget(user.id, formData); if ("error" in parsed) return parsed; await prisma.budget.create({ data: { ...parsed.data, userId: user.id } }); refreshBudgets(); return { success: true } }
export async function updateBudgetAction(_: BudgetFormState, formData: FormData): Promise<BudgetFormState> { const user = await requireUser(); const budgetId = String(formData.get("budgetId") ?? ""); if (!budgetId) return { error: "We could not find that budget." }; const exists = await prisma.budget.findFirst({ where: { id: budgetId, userId: user.id }, select: { id: true } }); if (!exists) return { error: "This budget is no longer available." }; const parsed = await validateBudget(user.id, formData, budgetId); if ("error" in parsed) return parsed; await prisma.budget.update({ where: { id: budgetId }, data: parsed.data }); refreshBudgets(); return { success: true } }
export async function deleteBudgetAction(formData: FormData) { const user = await requireUser(); const budgetId = String(formData.get("budgetId") ?? ""); if (!budgetId) return; await prisma.budget.deleteMany({ where: { id: budgetId, userId: user.id } }); refreshBudgets() }
